server:
  port: 8081
  servlet:
    context-path: /iam_service

spring:
  application:
    name: IAM Service
  datasource:
    url: jdbc:mysql://localhost:3306/iam-service-db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secretKey: "s/beSs9t6Hj9M1uAX1qq6AB1jKQW26HBzY8GZ2ts+bQqP9s7vO4q561zZejMQUgZ"


info:
  app:
    name: IAM Service App
    description: IAM Service with Spring Boot, PostgresSQL và JWT
    version: 1.0.0