server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/iams
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: cb9b9078d8efbf
    password: 472c361eaa061d
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

redis:
  host: localhost
  port: 6379

info:
  app:
    name: IAM Service App
    description: IAM Service with Spring Boot, PostgresSQL and JWT
    version: 1.0.0